In [3]:
#loading csv file
import pandas as pd

df = pd.read_csv("default of credit card clients.csv", header=1)
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [9]:
#🔍Check dataset
print(df.shape)
print(df.columns)

(30000, 25)
Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [7]:
df["default payment next month"].head()

0    1
1    1
2    0
3    0
4    0
Name: default payment next month, dtype: int64

In [8]:
#Clean column names (IMPORTANT Sometimes column name has spaces → fix it:)
df.columns = df.columns.str.strip()

In [11]:
#Reduce dataset to 4000 from 30,000
# Separate classes
fraud = df[df['default payment next month'] == 1]
normal = df[df['default payment next month'] == 0]

print("Fraud:", len(fraud))
print("Normal:", len(normal))

Fraud: 6636
Normal: 23364

Dataset is imbalanced

Safe customers = MANY
Risky customers = FEW

You are:
👉 Separating data into:

Risk group
Safe group

👉 Needed for:

Dataset reduction
AI logic

# BEFORE RENAMING "default payment next month"
default payment next month"
   This column name has:
Spaces 
Long name 
Easy to make mistakes 

#AFTER RENAMING "default payment next month"
Simple 
Clean 
No confusion

In [12]:
#REnaming
df.rename(columns={"default payment next month": "target"}, inplace=True)

In [13]:
df['target']

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: target, Length: 30000, dtype: int64

In [14]:
# majority vs minority risk check 0->safe, 1->risk
df['target'].value_counts()

target
0    23364
1     6636
Name: count, dtype: int64

In [15]:
#RECUDE DATASET
fraud = df[df['target'] == 1]
normal = df[df['target'] == 0]

print("Fraud:", len(fraud))
print("Normal:", len(normal))

Fraud: 6636
Normal: 23364

In [19]:
#Take samples
fraud_sample = fraud.sample(n=1000, random_state=42)
normal_sample = normal.sample(n=3000, random_state=42)

#Combine
df_small = pd.concat([fraud_sample, normal_sample])

#Shuffle
df_small = df_small.sample(frac=1, random_state=42)

#result
print(df_small.shape)

(4000, 25)

In [20]:
#Check balance
df_small['target'].value_counts()

target
0    3000
1    1000
Name: count, dtype: int64

In [21]:
#Save reduced dataset
df_small.to_csv("reduced_dataset.csv", index=False)

The dataset was reduced using stratified sampling to maintain class distribution 
while improving computational efficiency

In [22]:
#Check Missing Values : If all 0 → good
df_small.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
target       0
dtype: int64

In [23]:
#Drop unnecessary column (ID)
df_small.drop(columns=['ID'], inplace=True)

In [24]:
#Basic understanding
df_small.describe()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,target
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,...,4000.000000,4000.000000,4000.000000,4000.000000,4.000000e+03,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,168470.000000,1.602000,1.859750,1.543750,35.785250,-0.004500,-0.135750,-0.163250,-0.204750,-0.270250,...,44140.988500,40822.693750,39177.173000,5168.972500,6.241470e+03,5492.583500,4857.258750,4688.614750,5454.288500,0.250000
std,131036.833612,0.489547,0.775068,0.524075,9.378386,1.131503,1.194855,1.206426,1.196948,1.151541,...,67404.142097,63059.731708,61359.393292,18289.155975,2.810053e+04,22419.210258,17861.475704,14124.236329,18494.400507,0.433067
min,10000.000000,1.000000,1.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-65167.000000,-46627.000000,-339603.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2040.250000,1612.000000,1150.750000,810.000000,6.507500e+02,333.250000,243.750000,169.250000,112.000000,0.000000
50%,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,18434.000000,17290.000000,16779.000000,2061.500000,2.000000e+03,1718.500000,1500.000000,1545.000000,1500.000000,0.000000
75%,240000.000000,2.000000,2.000000,2.000000,42.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,55358.250000,49598.000000,48478.750000,5001.250000,5.000000e+03,4500.000000,4000.000000,4009.250000,4000.000000,0.250000
max,720000.000000,2.000000,6.000000,3.000000,74.000000,8.000000,7.000000,7.000000,7.000000,7.000000,...,628699.000000,484612.000000,466570.000000,873552.000000,1.215471e+06,889043.000000,621000.000000,330982.000000,345293.000000,1.000000

In [25]:
#Check duplicates
df_small.duplicated().sum()

np.int64(2)

In [26]:
#Remove those 2 duplicates
df_small = df_small.drop_duplicates()

In [27]:
#Check again
df_small.duplicated().sum()

np.int64(0)

In [29]:
#Check new dataset size
df_small.shape 
df_small.values

array([[200000,      2,      3, ...,    316,    316,      1],
       [240000,      2,      2, ...,   1546,   4390,      0],
       [ 80000,      2,      2, ...,   3000,   3000,      1],
       ...,
       [ 10000,      1,      2, ...,   1308,      0,      1],
       [ 60000,      2,      2, ...,  29484,   1326,      0],
       [280000,      2,      1, ...,   2000,   2000,      0]],
      shape=(3998, 24))

Data preprocessing was completed by cleaning the dataset, correcting column 
structures, renaming attributes, reducing dataset size using stratified sampling, 
removing duplicate entries, and validating the dataset for further AI-based analysis